### ISSUE TITLE
Implementing Prefetch for a given Queue using AsyncConsumer

### ISSUE THREAD

**Issue by DavidSantacruzR** [gftea/amqprs#102]
Hi there, it's been quite fun to work with your library. Currently, I started wondering if it's possible to use prefetch for a queue that uses basic_consume.

I've tried something along the lines:

```rust
       my_channel.basic_qos(
            BasicQosArguments::new(
                0,0,false
            )
        );
        my_channel.channel
            .basic_consume(callback, args)
            .await
            .unwrap();
```

For this do I need to implement the Blocking consumer instead?

Kind regards,

Dave.

**Comment by michaelklishin** [comment]
There is no such concept as a "queue prefetch" in the protocol. There is one [per consumer](https://rabbitmq.com/consumer-prefetch.html) but the recommendation from the RabbitMQ team is to use separate channels and the standard prefetch.

At least unless you need a lot of consumers (almost no one ever does).

**Comment by michaelklishin** [comment]
Please use Discussions for questions, they are no longer a new and unknown GitHub feature.
