### ISSUE TITLE
ChannelCallback::cancel() not called when server delete queue

### ISSUE THREAD

**Issue by OverworkedCriminal** [gftea/amqprs#112]
Hi,

I'm trying to detect unexpected consumer cancellations.
Based on https://www.rabbitmq.com/consumer-cancel.html
ChannelCallback::cancel() seems to be the best for this, but I can't make it work.

I tried doing something like this:
1. open connection
2. register connection callback
3. open channel
4. register channel callback
5. declare queue
6. channel.basic_consume(...)
7. remove queue using rabbitmqctl

But ChannelCallback::cancel() was not called.

<b>Did I miss some configuration?</b>

### Probable cause

I've read here https://www.rabbitmq.com/connections.html#capabilities
that this extension (consumer_cancel_notify) needs to be present in client capabilities, otherwise RabbitMQ does not send any notification.

I modified Connection::open() to check if it would help, and <b>it did</b>. 
![amqprs missing client capabilities](https://github.com/gftea/amqprs/assets/82613828/d3530265-31ae-450f-9bf8-07a9740afd57)

versions:
Rust: 1.73
amqprs: 1.5.0

**Comment by lukebakken** [comment]
Thank you - good job investigating this issue!

**Comment by OverworkedCriminal** [comment]
I opened pull request https://github.com/gftea/amqprs/pull/113 (not sure how to link it to this issue)
I'll see if i can write test for it

**Comment by lukebakken** [comment]
@OverworkedCriminal thank you!
