### ISSUE TITLE
[feature request] Missing heartbeat should trigger an I/O failure

### ISSUE THREAD

**Issue by rtxm** [gftea/amqprs#125]
If the link is dropped between the client and the broker (router failure, VPN disconnect, etc…), the TCP connection remains open (*Established*) but nothing pass through. The heartbeat is meant to detect that condition, and we'd like to reset the connection on the client side, as the broker do on its own side of the link.

**Comment by gftea** [comment]
Hi, indeed we can add it.
Is TCP keepalives enabled on your machine?

**Comment by rtxm** [comment]
TCP keepalives is system wide and would impact all services, whereas we can set the AMQP heartbeat per application (per connection actually!) depending on requirements.

**Comment by gftea** [comment]
@rtxm , please check if this is working for your use cases

**Comment by rtxm** [comment]
It does! Thanks!
