### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by LockedThread** [gftea/amqprs#131]
Is this library production ready? Is there built-in autorecovery from lost connections to RabbitMQ? I am exploring the usage of this library for a work project and need to report this information in our docs.

**Comment by so-schen** [comment]
Hi, for connection recovery can be done by using https://docs.rs/deadpool-amqprs/latest/deadpool_amqprs/
this library is implementing the core, and try to minimize deps, so user can tailor their need.
It is being used in production in HuggerFace and CapitalOne as I know

**Comment by LockedThread** [comment]
> Hi, for connection recovery can be done by using https://docs.rs/deadpool-amqprs/latest/deadpool_amqprs/ Also you can have a simple one without deps, https://github.com/cdbennett/amqprs-reconnect-example this library is implementing the core, and try to minimize deps, so user can tailor their need. It is being used in production in HuggerFace and CapitalOne as I know. Also it is tested thoroughly

Thanks for the info.
