### ISSUE TITLE
Quick question!

### ISSUE THREAD

**Issue by Theodlz** [gftea/amqprs#136]
Hi! I'm planning on using your package for an application that will potentially go to production at some point (for research in academia, no financial goals whatsoever), so I was wondering how active the development of your package is likely to be. By that I mean how often can we expect releases and updates (every month, year, none at all, ...), and if opening issues here is the way to go if we have bugs or new features in mind? 

Happy to contribute myself too when needed , of course.

**Comment by michaelklishin** [comment]
As client libraries mature, there won't be enough to do a monthly release. GitHub has the Pulse tab which demonstrates repository activity (mostly to weed out repositories that have been abandoned).

I can't speak for the frequency of releases but it is the Rust client Team RabbitMQ recommends and even without much of our help, this is very clearly not a piece of abandonware.

**Comment by gftea** [comment]
Thanks @michaelklishin :)
And this library goal is to keep simplicity with minimum dependencies and aims for production from day one. 
Any bug report is welcome to raise, feature request depending on if it’s core or not. Because protocol is stable, I would not expect any big changes would occur

**Comment by Theodlz** [comment]
Thanks for your answer both! This all sounds very reasonable to me.

I'll probably provide feedback soon-ish when I figure out a few things with the work queues.

Until then thanks a lots! Closing this issue.
