### ISSUE TITLE
No heartbeats sent with long-running consume functions?

### ISSUE THREAD

**Issue by dtebbs** [gftea/amqprs#138]
I have a client which accepts "requests", executes a long running computation (several minutes) and then writes the result to a response queue before ack-ing the original request.  I have set the tokio runtime to multi-threaded, 2 worker threads, and the prefetch for the request queue is 1.

Since the `consume` function is `async`, I assumed that heartbeats would automatically be sent while I am processing requests.  I also tried `spawn`ing in the handler to do the processing.  However if the processing lasts long enough then the rabbitmq server closes my connection due to lack of heartbeat.

I'm not very familiar with the protocol or the amqprs implementation, so I'm wondering if this is expected and I must set the heartbeat timeout much higher, or should heartbeats be sent by other tasks while processing is going on and I'm doing something wrong?

Thanks in advance for any advice.

**Comment by jmrgibson** [comment]
I was under the impression that you had to manually send something for the heartbeat (in 1.5 at least). I've been doing

```rust
                tokio::task::spawn_local({
                    async move {
                        let interval: u64 = (connection.heartbeat() / 2).into();
                        loop {
                            time::sleep(time::Duration::from_secs(interval - 1)).await;
                            if let Err(error) = channel.flow(true).await {
                                error!("Error while sending heartbeat: {}", error);
                                break;
                            }
                        }
                    }
                });
```

and then handling the task exit as one of my failure conditions

**Comment by dtebbs** [comment]
Thanks @jmrgibson that is extremely helpful. Will give this a shot.

**Comment by gftea** [comment]
if you are using tokio and your task is doing long-running blocking computation, it will block whole runtime to shedule other tasks, you should run it in blocking context instead of async context.
the heartbeat does send automatically by the lib.

**Comment by dtebbs** [comment]
Thanks for your help @gftea .  
Will ensure the tokio threads don't block and remove the manual heartbeats.
