### ISSUE TITLE
Setting Policy

### ISSUE THREAD

**Issue by US579** [gftea/amqprs#139]
hey is there a way to set policy when declaring an exchange?

<img width="1042" alt="Screenshot 2024-07-17 at 12 05 09 AM" src="https://github.com/user-attachments/assets/37ec08dc-5dad-42c5-93cd-0d5a8a19fa75">

**Comment by LockedThread** [comment]
I did some light research, it doesn't seem like policy is a part of the Advanced Message Queuing Protocol (AMQP). Is there another library, even in a different language, that lets you set the policy?

**Comment by michaelklishin** [comment]
Note that discussions are enabled in this repo. This should have been a discussion and not an issue.

@US579 AMQP 0-9-1 (messaging clients) do not set policies. You likely misunderstand how policies in RabbitMQ work and [why they exist](https://www.rabbitmq.com/docs/parameters#policies). You do not set a policy when declaring an exchange, you declare a policy with a pattern that matches the names of the objects you declare (such as exchanges)

@LockedThread only HTTP API clients do, such as [this one for Rust](https://github.com/michaelklishin/rabbitmq-http-api-rs).

**Comment by LockedThread** [comment]
> Note that discussions are enabled in this repo. This should have been a discussion and not an issue.
> 
> @US579 AMQP 0-9-1 (messaging clients) do not set policies. You likely misunderstand how policies in RabbitMQ work and [why they exist](https://www.rabbitmq.com/docs/parameters#policies). You do not set a policy when declaring an exchange, you declare a policy with a pattern that matches the names of the objects you declare (such as exchanges).
> 
> @LockedThread only HTTP API clients do, such as [this one for Rust](https://github.com/michaelklishin/rabbitmq-http-api-rs).
I figured as much. Thanks for clearing this up.

**Comment by LockedThread** [comment]
@gftea can you close this
