### ISSUE TITLE
TLS connection with AWS RabbitMQ hard to setup

### ISSUE THREAD

**Issue by nmapx** [gftea/amqprs#149]
Hey

I'm trying to setup my app to work with Rabbit running on AWS
AWS requires TLS connection but it seems to be very hard to configure using this library
Could you please assist and share some more details on how to do that?
Most libraries across different languages require just `skip_ssl_verification` or `trust_certificates` or similar - is anyting like that possible here?

I've tried using `TlsAdaptor::without_client_auth` with first param as `None` (i do not have ca certificate - AWS does not provide ones) and domain set to the Rabbit hostname
This produces error `message broker: network io error: received corrupt message`
I would really appreciate some help

**Comment by gftea** [comment]
try to find aws way to setup root store
I found this https://docs.aws.amazon.com/sdk-for-rust/latest/dg/enforcing-tls.html

**Comment by SignalWhisperer** [comment]
I was able to successfully connect to my Amazon MQ for RabbitMQ broker using the following:
```rust
    let mut args = OpenConnectionArguments::new(
        "b-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.mq.us-east-1.amazonaws.com",
        5671,
        "username",
        "password",
    );
    let args = args
        .tls_adaptor(TlsAdaptor::without_client_auth(None, args.get_host().to_owned()).unwrap())
        .finish();

    let connection = Connection::open(&args).await.unwrap();
    connection
        .register_callback(DefaultConnectionCallback)
        .await
        .unwrap();
```

The rest of the code is taken straight from this example: [tls.rs](https://github.com/gftea/amqprs/blob/main/examples/src/tls.rs)

Amazon MQ for RabbitMQ does not support mutual TLS, so client authentication is not supported.

If you do not have a trust store available, you can build one using the Amazon root CAs: <https://www.amazontrust.com/repository/>

**Comment by michaelklishin** [comment]
@nmapx first of all, this should have been a discussion.

TLS can be used in different ways, namely peer verification can be disabled for the server (it won't verify the client's certificate chain). Assuming what you want to do is to make the client verify the certificate, then using [`tls-gen`](https://github.com/rabbitmq/tls-gen)-produced certificates for clients might be enough.

Plus, when I have asked this in one of the contributor chats on community Slack, @SignalWhisperer has shared https://www.amazontrust.com/repository/.
