### ISSUE TITLE
Does it fully support RabbitMQ 4.0

### ISSUE THREAD

**Issue by nine-city** [gftea/amqprs#150]
Does it fully support RabbitMQ 4.0

**Comment by michaelklishin** [comment]
There is nothing for this client to "fully support" in RabbitMQ 4.0. Any AMQP 0-9-1 client released after 2011 or so should be able to connect, authenticate and perform all fundamental operations.

What the removal of classic queue mirroring means for clients is [documented in release notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.1) and there isn't anything a client library can do about it. For non-mirrored classic queues, nothing changes. For quorum queues and streams, nothing changes.

The same goes for the section entitled "AMQP 0.9.1 x-death header".

**Comment by michaelklishin** [comment]
@nine-city this repository has Discussions enabled, please use them instead of filing issues for questions. Using issues for questions in late 2024 is just rude.
