### ISSUE TITLE
feature request: long-lived Consumer example

### ISSUE THREAD

**Issue by McPatate** [gftea/amqprs#18]
Hello 👋🏻 

I'm trying to create a consumer that will be running until an error happens on the rabbitmq connection (so it should technically never stop).

I'm currently having an issue where the connection is dropped and the way I found around that was to loop on the `basic_get` call. Looking at the code this feels inefficient compared to `basic_consume` (and also it does say in the amqp reference that it's not efficient).

I've tried going about this issue with the following code:

```rs
loop {
    tokio::time::sleep(Duration::new(2, 0));
}
```

But it seems the connection object I have still gets dropped for some reason.

Happy to share more code and/or discuss it but I'd gladly take a working example if you have one ready !

**Comment by gftea** [comment]
Hi, 

you can have a look at [basic_consumer](https://github.com/gftea/amqprs/blob/main/amqprs/examples/basic_consumer.rs).

Run the example with "traces" feature enabled to see traces
`$ cargo run --features traces --example basic_consumer`

After consumer starts, you can run a publisher, make sure to match the exchange and routing key used in consumer.

If you just want a quick test, you can run the integration test [test_publish](https://github.com/gftea/amqprs/blob/main/amqprs/tests/test_publish.rs)

you should see the traces like below

`2022-12-29T20:47:27.392541Z  INFO amqprs::api::consumer: consume delivery Deliver: consumer_tag = basic_consumer, delivery_tag = 10000, redelivered = false, exchange = amq.topic, routing_key = amqprs.example on channel 1 [open] of connection AMQPRS000@localhost:5672/ [open]
`

**Comment by McPatate** [comment]
The `tokio::sync::Notify` works like a charm, thank you !
