### ISSUE TITLE
Typo in Compliance Assert feature

### ISSUE THREAD

**Issue by jacobmiller22** [gftea/amqprs#21]
The `compliance_assert` feature is listed as `compliance_assert` in `amqprs/Cargo.toml`, but in the code where the features are toggled with `#[cfg(feature = "compilance_assert")]`. See the transposition error in `compliance` vs `compilance`. Is this intentional? Also, the module is listed as `compilance_assert.rs`. This may be correct, but it seems like this would cause a disconnect?

**Comment by gftea** [comment]
oh... they are exactly typo, not intentional :)
