### ISSUE TITLE
Ignore Local RabbitMQ Secrets 

### ISSUE THREAD

**Issue by jacobmiller22** [gftea/amqprs#24]
Hi, I wanted to present an issue and propose a potential solution that will make the dev experience better. Currently, the local secrets for the RabbitMQ configuration are being tracked by git, and are independent across machines. This makes all contributors `rabbitmq_conf` directories different than @gftea 's. Since the certs get generated by the `start_rabbitmq.sh`, we can add the `rabbitmq_conf` directory to the git ignore and modify the `start_rabbitmq.sh` script to create the `rabbitmq_conf` directory in the case it doesn't exist (Will happen on a fresh clone). Without this, contributors local repositories will never be up to date with main: see snippet of my git status below. Additionally, I had to change the permission of these files when I first cloned the repository in order to execute the scripts.

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   rabbitmq_conf/client/ca_certificate.pem
        modified:   rabbitmq_conf/client/ca_key.pem
        modified:   rabbitmq_conf/client/client_AMQPRS_TEST_certificate.pem
        modified:   rabbitmq_conf/client/client_AMQPRS_TEST_key.p12
        modified:   rabbitmq_conf/client/client_AMQPRS_TEST_key.pem
        modified:   rabbitmq_conf/server/ca_certificate.pem
        modified:   rabbitmq_conf/server/ca_key.pem
        modified:   rabbitmq_conf/server/server_AMQPRS_TEST_certificate.pem
        modified:   rabbitmq_conf/server/server_AMQPRS_TEST_key.p12
        modified:   rabbitmq_conf/server/server_AMQPRS_TEST_key.pem

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        rabbitmq_conf/client/client_AMQPRS_TEST.p12
        rabbitmq_conf/server/server_AMQPRS_TEST.p12

no changes added to commit (use "git add" and/or "git commit -a")
```

Is there any downside? If not, I would be happy to begin working on this solution.

**Comment by gftea** [comment]
LGTM, please go ahead @jacobmiller22

**Comment by gftea** [comment]
You will also need to update the github workflow files to call the updated script start_rabbitmq.sh
```
    - name: Start RabbitMQ server
      run:  |
        sudo chown -R 1001:root rabbitmq_conf/server
        sudo chmod 755 rabbitmq_conf/server
        sudo chmod 400 rabbitmq_conf/server/*
        docker-compose up -d
```

**Comment by jacobmiller22** [comment]
> You will also need to update the github workflow files in `.github/workflows` to call the updated script `start_rabbitmq.sh, `currently it assume the `rabbitmq_conf `exists```

Ah yes thank you. I was not sure where that code was.
