### ISSUE TITLE
Performance test tools in repo.

### ISSUE THREAD

**Issue by jacobmiller22** [gftea/amqprs#35]
I think it would be valuable to have some infrastructure in place to allow for performance testing. This would let us see where this library compares to other RabbitMQ clients and will help quantify performance increases (and potential decreases) version to version or while developing. I don't have any specific tools in mind and will begin researching if this idea is given the green light. Do you think this idea is worth adding? This idea was inspired by your change that reduces the number of syscalls (#33) and I am curious how much of a performance increase was achieved by the reduction of syscalls.

**Comment by michaelklishin** [comment]
You can use PerfTest for baseline comparison or develop a minimalistic implementation of PerfTest (the library part).

It's a non-trivial amount of effort but Team RabbitMQ did it for .NET for similar reasons.

**Comment by michaelklishin** [comment]
We don't really store baseline data, you would have to run PerfTest in your environment yourself. A basic 1 consumer, one producer, one quorum queue kind of workload would be enough to start.

**Comment by gftea** [comment]
I take a quick look of [perftest](https://github.com/rabbitmq/rabbitmq-perf-test),  it seem by default using java client and mainly target for server performance test.

**Comment by michaelklishin** [comment]
Yes but you can also use it as a library and certainly can use it to establish a baseline for your client

**Comment by McPatate** [comment]
We use https://docs.rs/criterion/latest/criterion/ @ HuggingFace for our [tokenizers](https://github.com/huggingface/tokenizers) library :)

**Comment by gftea** [comment]
@jacobmiller22 I setup a benchmark comparison between amqprs vs lapin, and it shows amqprs performance is much better than lapin in a basic_publish case.
if you are interesting, you can check https://github.com/gftea/amqprs/actions/runs/4142767627/jobs/7163827661

**Comment by jacobmiller22** [comment]
@gftea Thanks for working on this. I was meaning to contribute, but just got caught up in some other personal stuff. Congrats on the better performance! If you have any suggestions on how to improve the test tools or any quality of life, I'd love to give it a stab.

**Comment by gftea** [comment]
I have added 3 different benchmarking methods, I will close the ticket now considering this is to first introduction of benchmarking.
