### ISSUE TITLE
RPC/request + reply example

### ISSUE THREAD

**Issue by brandonros** [gftea/amqprs#42]
I feel like this repo would benefit from this. If I made a mistake or didn't follow a best practice and this isn't how this should be achieved in a "production" setting, I'd love to learn.

https://github.com/brandonros/rabbitmq-rpc-rs

**Comment by gftea** [comment]
@brandonros , thanks for the idea, would you like to submit a PR to add an example?

**Comment by brandonros** [comment]
were you able to check out the repo link i edited to? what are your thoughts?

**Comment by gftea** [comment]
I think we can add a link to your example repo in REWADME file
