### ISSUE TITLE
Not able to run tests on Mac M1

### ISSUE THREAD

**Issue by raymundovr** [gftea/amqprs#65]
Hi,

I've been willing to take on #62 and before I want to be able to run the integration tests.

However I'm facing two main issues:

1. On `start_rabbitmq.sh` the permissions  do not apply on my Mac OS installation, `UID=1001` is not valid, which makes the process throw errors, although not stopping.
2. The bitnami rabbitmq image does not boot. I just get a ` ERROR ==> Couldn't start RabbitMQ in background.` I've been trying to run it in isolation (simple docker composer) without any different result.  The official rabbitmq image works though.

Any recommendations?

**Comment by gftea** [comment]
Can the bitnami rabbitmq starts up without TLS config?

**Comment by raymundovr** [comment]
@gftea unfortunately not, that's what I meant with "been trying to run it in isolation".

**Comment by gftea** [comment]
We can report issues to https://github.com/bitnami/containers

**Comment by jacobmiller22** [comment]
@raymundovr can you not just run the official rabbitmq container (with similar config) and use that for the `./regression_test`? Sorry if I may be mistaken.

**Comment by raymundovr** [comment]
I'll check it when I have some time.
Will close this for now as it might not be related to this project.
