### ISSUE TITLE
feat: consumer APIs improvements

### ISSUE THREAD

**Issue by gftea** [gftea/amqprs#68]
### API breaking changes
1.  `basic_consume` and `basic_consume_blocking` to return task `JoinHanlder` to user, so that user can check task failure
2.   current `basic_consume_rx` return `ConsumerMessage`  type which have unnecessary `Option` wrapper for fields. We should define a new message type to be used for user, and and keep internal message buffering type hidden

**Comment by quantum-booty** [comment]
It would be nice to have the ability to receive a batch of messages of a given size.

**Comment by gftea** [comment]
The AMQP protocol itself does not have such functionality. I can see this can be achieved easily by user via wrapping `UnboundedReceiver` returned from `basic_consume_rx`  in `UnboundedReceiverStream` and handle the application logic themselves

**Comment by quantum-booty** [comment]
> The AMQP protocol itself does not have such functionality. I can see this can be achieved easily by user via wrapping `UnboundedReceiver` returned from `basic_consume_rx` in `UnboundedReceiverStream` and handle the application logic themselves

I think it would be good to add this in the examples, its not very obvious and did take me some research to come across the UnboundedReceiverStream. I'm happy to make a PR.

**Comment by gftea** [comment]
You are welcome to submit PR

**Comment by cdbennett** [comment]
Just here to watch the label battle with the bot 😄
