### ISSUE TITLE
Error running the publisher subsriber example.

### ISSUE THREAD

**Issue by DavidSantacruzR** [gftea/amqprs#73]
Hi, I am building an adapter to your library, but for that I need to fully understand your project. So, I was running your examples, but encountered a problem with the publisher subscriber example.

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NetworkError("network io error: Connection reset by peer (os error 54)")'
```

I am running rust 1.68 on macOs. Also, I am using the following command to start my rabbitMQ local server ```zsh rabbitmq-server```

Should I need to specify something else when starting the rabbit server instance?

Thank you in advance, and have a nice day.

**Comment by gftea** [comment]
Have you started rabbitmq server locally?

**Comment by DavidSantacruzR** [comment]
That's correct.

**Comment by DavidSantacruzR** [comment]
Thanks for the clarification.
