### ISSUE TITLE
Consumer immediately gets closed

### ISSUE THREAD

**Issue by gabrielgrover** [gftea/amqprs#79]
Hello all,  I am trying to create a basic consumer in my application.  I placed two break points
- https://github.com/gftea/amqprs/blob/main/amqprs/src/api/channel/basic.rs#L629
- https://github.com/gftea/amqprs/blob/main/amqprs/src/api/channel/basic.rs#L640

The first pause is in the `None` match arm.  I cannot figure out why [consumer_tx](https://github.com/gftea/amqprs/blob/main/amqprs/src/api/channel/basic.rs#L656) is getting dropped.  Maybe there is something I am doing wrong?  Have any of you seen this before?  Another interesting thing I see, is that when I restart the container everything seems to be fine.  The `consumer_tx` is not dropped and my consumer impl gets messages like i would expect it too.

**Comment by gftea** [comment]
Is your channel instance kept from dropping , I would guess your channel instance drop first which cause dispatcher drops .

Can you run your test with "trace" level
