### ISSUE TITLE
BasicProperties: expose delivery mode (persistent vs. transient) as a boolean or enum

### ISSUE THREAD

**Issue by michaelklishin** [gftea/amqprs#80]
Right now it is a u8 or something like that. Other clients have long moved to expose a boolean (or an enum).

**Comment by michaelklishin** [comment]
I can see how introduction of a new type that has `From`/`Into` implementations for `Octet` and boolean (or the new enum) may even retain backwards (source) compatibility. WDYT?

**Comment by gftea** [comment]
@michaelklishin thanks for raising the improvement idea, 
it sounds a good idea for me, as long as we maintain backward compatibility, otherwise we need to target release v2.

**Comment by michaelklishin** [comment]
I think adding a new builder method with a different name would be the best path to go about it. I'll submit a PR.
