### ISSUE TITLE
"Alternative default: queue declaration arguments

### ISSUE THREAD

**Issue by michaelklishin** [gftea/amqprs#81]
`QueueDeclareArguments` uses the builder pattern and that's nice but it would be even better
to also provide a few constructor/factory methods for common cases:

 * Durable (and thus non-exclusive, non-autodelete) queue
 * Transient exclusive queue
 * Transient auto-delete queue

Clients such as Bunny provide such helpers.

I'd be happy to submit a PR if it'd be accepted.

**Comment by gftea** [comment]
@michaelklishin , sounds good to me!
