### ISSUE TITLE
BasicPublishArguments: deprecate the immediate field

### ISSUE THREAD

**Issue by michaelklishin** [gftea/amqprs#82]
Support for the `immediate` flag was removed in RabbitMQ 3.0 because it is impossible to implement in ways that do not ruin throughput of multi-node clusters (the node handling `basic.publish` had to communicate with peers for every message published).

I suggest that we make the field private and thus remove it from the API.

**Comment by gftea** [comment]
because it is public in released version, would need to make it `deprecated` otherwise it is backward incompatible.
How about add above limitation to explain why it is deprecated and discouraged to use, also good for user to know the history.

**Comment by michaelklishin** [comment]
Right, deprecating might be enough, even though I am quite certain nobody out there uses the flag: RabbitMQ will report an unrecoverable (connection) error if you try.
