### ISSUE TITLE
BasicConsumeArguments: rename no_ack since it is confusing

### ISSUE THREAD

**Issue by michaelklishin** [gftea/amqprs#83]
While `no_ack` is indeed a protocol-level field name, it is confusing. For `basic.consume` in the API, other clients have generally adopted "auto ack" for the name (or "manual ack", which I like even more).

So I suggest that the field is renamed to `auto_ack` and a convenience method (default) is introduced for both modes.

Happy to work on a PR if it would be accepted.

**Comment by gftea** [comment]
rename the public field is also backward compatible, do you have proposal to make a backward compatible change?

**Comment by michaelklishin** [comment]
Well, the builder pattern can have one more method. Maybe without using the macro that defines all methods right now.

More importantly, after we introduce a new method, all examples should be updated to use it.

**Comment by gftea** [comment]
Good to me.
I meant rename public field is non-backward compatible
