### ISSUE TITLE
Address (most) clippy warnings

### ISSUE THREAD

**Issue by michaelklishin** [gftea/amqprs#87]
A lot of `cargo clippy` warnings are unused variables and trivial things like that. Should I submit a PR that squashes as many of them as possible within a certain time box (say, a couple of hours)?

**Comment by michaelklishin** [comment]
Now I understand why: most warnings come from conditionally compiled code like this:

```
Err(err) => {
  #[cfg(feature="traces")]
  error!("cancel callback error on channel {}, cause: '{}'.", self.channel, err);
}
```

**Comment by gftea** [comment]
If compiles with all features, it should be no warning

**Comment by michaelklishin** [comment]
> If compiles with all features, it should be no warning

Fair enough.
