### ISSUE TITLE
FieldTable needs a convenience method for instantiation from a map

### ISSUE THREAD

**Issue by michaelklishin** [gftea/amqprs#93]
It's fairly unusual for users to think of how many entries there are in their map. I think `FieldTable` needs one more constructor method.

**Comment by gftea** [comment]
Hi, can you elaborate further?

**Comment by michaelklishin** [comment]
Fair enough, my intuition from other clients was to instantiate a map and pass it on or convert it to `FieldTable` but I guess instantiating it and then populating it as a map is just as fair.
