### ISSUE TITLE
Best practices for opening channel, and prevent it from being dropped.

### ISSUE THREAD

**Issue by DavidSantacruzR** [gftea/amqprs#99]
I'm building a wrapper to your library, and recently came across a problem to prevent a channel connection from being dropped.
So, the question is, should each queue have their own channel or is it better to have one channel, and bind multiple queues to it?

Which one is considered bad practice?

For example:

Approach: **one**

```rust
struct MyConsumer {
        connection: Connection
        channels: Vec<Channel>   
}


impl MyConsumer {

    fn create_channel(&mut self, queue: String) -> Channel {
           /* logic to create, and bind a channel goes here, pushes to vector */

    }

}

```

Approach: **two**

```rust
struct MyConsumer {
        connection: Connection
        channel: Channel  
}

impl MyConsumer {

    fn create_channel(&mut self, queue: String) {
           /* creates queue and binds it to one channel*/

    }

}
```

My problem with my current approach is that when binding a queue to a channel, I'm unable to prevent the channel from being dropped.

Any advice is much appreciated.

**Comment by gftea** [comment]
see guideline provided by rabbit community https://github.com/gftea/amqprs/discussions/78#discussioncomment-5524344

**Comment by michaelklishin** [comment]
Besides the guides, I don't see any issue with treating channels as resources (as if it was a file or socket) and make your consumer implementation own it. Then you will have to make sure the consumer instance lives long enough.

However, you can also initialize the connection(s), channel(s) and connection recovery code in the `main` or similar code path in your app, and make consumers borrow them.
